import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProfileCard from "./component/Profile/Profile";
import * as React from 'react';
import Button from '@mui/material/Button';
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prateek portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="leftside">
          <ProfileCard />
        </div>
        <div className="rightside">
          <div className='bar'>
            <Button className="butt">
              <Link href='/' >HOME</Link>
            </Button>
            <Button className="butt">
              <Link href='/resume'>RESUME</Link>
            </Button>
            <Button className="butt">
              <Link href='/project'>PROJECT</Link>
            </Button>
            <Button className="butt">
              <Link href='/contact'>CONTACT</Link>
            </Button>
          </div>
          <div className="mainbody">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
